name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Sync files to the S3 bucket
    - uses: jakejarvis/s3-sync-action@v1
      with:
        args: --acl public-read --follow-symlinks --delete --exact-timestamps
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'
        SOURCE_DIR: 'website'

